-- 코드를 입력하세요
WITH COST AS (
    SELECT A.DAILY_FEE, A.CAR_TYPE, B.HISTORY_ID, DATEDIFF(B.END_DATE, B.START_DATE) + 1 AS DAY,
    CASE
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE 'NONE'
    END AS DURATION_TYPE
    
    FROM CAR_RENTAL_COMPANY_CAR AS A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭'
)

SELECT COST.HISTORY_ID, ROUND(COST.DAILY_FEE * COST.DAY * (100 - IFNULL(C.DISCOUNT_RATE, 0))/ 100) AS FEE
FROM COST
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON COST.DURATION_TYPE = C.DURATION_TYPE AND COST.CAR_TYPE = C.CAR_TYPE
ORDER BY FEE DESC, COST.HISTORY_ID DESC
