-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM APPOINTMENT AS C
JOIN PATIENT AS A ON C.PT_NO = A.PT_NO
JOIN DOCTOR AS B ON C.MDDR_ID = B.DR_ID
WHERE C.MCDP_CD = 'CS' AND C.APNT_YMD LIKE '2022-04-13%' AND C.APNT_CNCL_YMD IS NULL
ORDER BY C.APNT_YMD